CREATE TABLE NHACC(
    ID_NHACC NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_NHACC NVARCHAR(100) NOT NULL,
    DIA_CHI NVARCHAR(250),
    SO_DTH VARCHAR(20),
);
GO

CREATE TABLE KHACHHANG (
    ID_KH NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_KH NVARCHAR(100) NOT NULL, 
    SO_DTH VARCHAR(20) UNIQUE,
    DIA_CHI NVARCHAR(250),
    THANH_PHO NVARCHAR(50),
    QUOC_GIA NVARCHAR(50),
    DIEM_TICH_LUY INT DEFAULT 0,
	TRANG_THAI INT NOT NULL DEFAULT 1,
);
GO

CREATE TABLE SHIPPER(
    ID_SHIPPER NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_HANG_SHIPPER NVARCHAR(100) NOT NULL,
    SO_DTH VARCHAR(20),
);
GO

CREATE TABLE SAN_PHAM (
    ID_SANPHAM NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_SANPHAM NVARCHAR(100) NOT NULL, 
    ID_NHACC NVARCHAR(10) NOT NULL,
    DON_VI NVARCHAR(50),
    GIA_BAN MONEY NOT NULL,
    NGAY_SX DATE,
    LOAI_HANG NVARCHAR(50),
    NOI_SX NVARCHAR(100),
	TRANG_THAI_KD INT NOT NULL DEFAULT 1,

    CONSTRAINT FK_SAN_PHAM_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC)
);
GO

CREATE TABLE KHO_HANG(
    ID_SANPHAM NVARCHAR(10) PRIMARY KEY NOT NULL,
    SO_LUONG INT NOT NULL DEFAULT 0,
	MUC_CANH_BAO INT DEFAULT 10, -- CẢNH BÁO HÀNG TỒN KHO
    
    CONSTRAINT FK_KHO_HANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM)
);
GO

CREATE TABLE NHAP_HANG(
    ID_PHIEUNHAP NVARCHAR(10) PRIMARY KEY NOT NULL,
    ID_NHACC NVARCHAR(10) NOT NULL,
    NGAY_NHAP DATE DEFAULT GETDATE(),

    CONSTRAINT FK_NHAP_HANG_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC),
);
GO

CREATE TABLE CHI_TIET_NHAP_HANG (
    ID_PHIEUNHAP NVARCHAR(10) NOT NULL,
    ID_SANPHAM NVARCHAR(10) NOT NULL,
    SO_LUONGNHAP INT NOT NULL,
    GIA_NHAP MONEY NOT NULL,

    PRIMARY KEY (ID_PHIEUNHAP, ID_SANPHAM),--Khóa chính TỔ HỢP
    CONSTRAINT FK_CHI_TIET_NHAP_HANG_PHIEUNHAP FOREIGN KEY (ID_PHIEUNHAP) REFERENCES NHAP_HANG(ID_PHIEUNHAP),
    CONSTRAINT FK_CHI_TIET_NHAP_HANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM)
);
GO


CREATE TABLE HOADON(
    ID_HOADON NVARCHAR(10) PRIMARY KEY NOT NULL,
    ID_KH NVARCHAR(10) NOT NULL,
    NGAY_TAO DATE DEFAULT GETDATE(),
    CHIETKHAU MONEY DEFAULT 0,
    TONG_TIEN_SP MONEY DEFAULT 0,
    TONG_THANH_TOAN MONEY DEFAULT 0,
    HINH_THUC INT NOT NULL DEFAULT 1, -- 1. ONLINE , 2. TẠI QUẦY
    TRANG_THAI INT NOT NULL DEFAULT 1, -- 1. mới tạo , 2. đang giao , 3.dã hoàn thành , 4. đã hủy
    
    ID_SHIPPER NVARCHAR(10) NULL,
    NGAY_GIAO_DU_KIEN DATE NULL,
    NGAY_GIAO_THUC_TE DATE NULL,
    
    CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH),
    CONSTRAINT FK_HOADON_SHIPPER FOREIGN KEY (ID_SHIPPER) REFERENCES SHIPPER(ID_SHIPPER)
);
GO

CREATE TABLE DON_HANG (
    ID_HOADON NVARCHAR(10) NOT NULL,
    ID_SANPHAM NVARCHAR(10) NOT NULL,
    SO_LUONGBAN INT NOT NULL DEFAULT 1,
    DON_GIA MONEY NOT NULL,
    
    PRIMARY KEY (ID_HOADON, ID_SANPHAM),

    CONSTRAINT FK_DON_HANG_HOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON),
	CONSTRAINT FK_DON_HANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM)
);
GO

CREATE TABLE LICH_SU_DIEM (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_KH NVARCHAR(10) NOT NULL,
    ID_HOADON NVARCHAR(10) NULL,
    SO_DIEM_THAY_DOI INT NOT NULL,
    LY_DO NVARCHAR(200),
    NGAY_TAO DATETIME DEFAULT GETDATE(),
    
    CONSTRAINT FK_LICH_SU_DIEM_KHACHHANG FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH),
    CONSTRAINT FK_LICH_SU_DIEM_HOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON)
);
GO

-- Type T_GioHang
CREATE TYPE T_GioHang AS TABLE (
    ID_SANPHAM NVARCHAR(10),
    SO_LUONGBAN INT,
    DON_GIA MONEY
);
GO

