CREATE DATABASE ban_hang_db;
GO

USE ban_hang_db;
GO


CREATE TABLE KHACHHANG(
    ID_KH NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_KH NVARCHAR(50),
    SO_DTH VARCHAR(20),
    DIA_CHI NVARCHAR(50),
    THANH_PHO NVARCHAR(50),
    QUOC_GIA NVARCHAR(50)
);
GO

CREATE TABLE NHACC(
    ID_NHACC NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_NHACC NVARCHAR(100),
    DIA_CHI NVARCHAR(50),
    SO_DTH VARCHAR(20)
);
GO

CREATE TABLE SAN_PHAM(
    ID_SANPHAM NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_SANPHAM NVARCHAR(50),
    ID_NHACC NVARCHAR(10),
    NGAY_SX DATE,
    LOAI_HANG NVARCHAR(50),
    GIA_BAN MONEY,
    NOI_SX NVARCHAR(100),
    CONSTRAINT FK_SANPHAM_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC)
);
GO

CREATE TABLE HOADON(
    ID_HOADON NVARCHAR(10) PRIMARY KEY NOT NULL,
    ID_KH NVARCHAR(10),
    NGAY_TAO DATE DEFAULT GETDATE(),
    TONG_TIEN MONEY DEFAULT 0,
    TRANG_THAI INT DEFAULT 1 NOT NULL,
    CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH)
);
GO

	CREATE TABLE DON_HANG(
    ID_HOADON NVARCHAR(10) NOT NULL,
    ID_SANPHAM NVARCHAR(10) NOT NULL,
    SO_LUONG_BAN INT,
    GIA_BAN MONEY,
    NGAY_BAN DATE DEFAULT GETDATE(),
    CONSTRAINT PK_DONHANG PRIMARY KEY (ID_HOADON, ID_SANPHAM),
    CONSTRAINT FK_DONHANG_HOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON),
    CONSTRAINT FK_DONHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM)
);
GO

CREATE TABLE KHO_HANG (
    ID_SANPHAM NVARCHAR(10) PRIMARY KEY,
    ID_NHACC NVARCHAR(10),
    SO_LUONG INT,
    TEN_SANPHAM NVARCHAR(50),
    GIA_NHAP MONEY,
    GIA_BAN MONEY,
    CONSTRAINT FK_KHOHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM),
    CONSTRAINT FK_KHOHANG_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC)
);
GO

CREATE TABLE PHIEU_NHAP(
    ID_PHIEUNHAP NVARCHAR(10) PRIMARY KEY NOT NULL,
    ID_NHACC NVARCHAR(10),
    NGAY_NHAP DATE DEFAULT GETDATE(),
    TONG_TIEN MONEY DEFAULT 0,
    CONSTRAINT FK_PHIEUNHAP_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC)
);

CREATE TABLE NHAP_HANG(
    ID_PHIEUNHAP NVARCHAR(10) NOT NULL,
    ID_SANPHAM NVARCHAR(10) NOT NULL,
    ID_NHACC NVARCHAR(10),
    SO_LUONG_NHAP INT,
    GIA_NHAP MONEY,
    LOAI_HANG NVARCHAR(50),
    NOI_SX NVARCHAR(100),
    NGAY_NHAP DATE DEFAULT GETDATE(),
    CONSTRAINT PK_NHAPHANG PRIMARY KEY (ID_PHIEUNHAP, ID_SANPHAM),
    CONSTRAINT FK_NHAPHANG_PHIEUNHAP FOREIGN KEY (ID_PHIEUNHAP) REFERENCES PHIEU_NHAP(ID_PHIEUNHAP),
    CONSTRAINT FK_NHAPHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SAN_PHAM(ID_SANPHAM),
    CONSTRAINT FK_NHAPHANG_NHACC FOREIGN KEY (ID_NHACC) REFERENCES NHACC(ID_NHACC)
);
GO

CREATE TABLE SHIPPER (
    ID_SHIPPER NVARCHAR(10) PRIMARY KEY NOT NULL,
    TEN_SHIPPER NVARCHAR(100),
    SO_DTH VARCHAR(20),
    TRANG_THAI INT DEFAULT 1
);
GO

CREATE TABLE TRANG_THAI(
    ID_HOADON NVARCHAR(10) PRIMARY KEY NOT NULL,
    ID_SHIPPER NVARCHAR(10),
    ID_SANPHAM NVARCHAR(10),
    NGAY_DAT DATE DEFAULT GETDATE(),
    NGAY_GIAO DATE,
    CONSTRAINT FK_TRANGTHAI_HOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON)
	CONSTRAINT FK_TRANGTHAI_SHIPPER FOREIGN KEY (ID_SHIPPER) REFERENCES SHIPPER(ID_SHIPPER)
);
GO
