CREATE TABLE NHA_CC (
	MA_NCC INT PRIMARY KEY NOT NULL, 
	TEN_NCC NVARCHAR(50),
	DIA_CHI NVARCHAR(100),
	SO_DTH INT
); 

CREATE TABLE MAT_HANG(
	MA_HANG INT PRIMARY KEY NOT NULL,
	TEN_HANG NVARCHAR(50),
	LOAI_HANG NVARCHAR(50),
	NOI_SX NVARCHAR(50)
)
CREATE TABLE PHIEU_NHAP(
	MA_NHAP INT PRIMARY KEY NOT NULL,
	NGAY_NHAP DATE NOT NULL DEFAULT GETDATE(), -- NẾU KHÔNG NHẬP NGÀY NHẬP HÀNG TỰ ĐỘNG LẤY GIỜ VÀ NGÀY HÔM ĐÓ
	MA_NCC INT NOT NULL,
	CONSTRAINT FK_PHIEU_NHAP_NCC FOREIGN KEY (MA_NCC) -- RÀNG BUỘC KHÓA NHÀ CUNG CẤP VỚI BẢNG PHIẾU NHẬP, SUY RA MUỐN NHẬP HÀNG THÌ PHẢI CÓ NHÀ CUNG CẤP TỒN TẠI VÀ KHÔNG BỊ TRÙNG LẶP 
	REFERENCES NHA_CC(MA_NCC)
)
CREATE TABLE NHAP_HANG(
	 MA_NHAP INT NOT NULL,
	 MA_HANG INT NOT NULL,
	 SO_LUONG INT NOT NULL CHECK (SO_LUONG > 0),
	 GIA_NHAP DECIMAL(9,3) NOT NULL CHECK (GIA_NHAP >= 0) -- DECIMAL NHAP TỐI ĐA 9 SỐ TRƯỚC DẤU PHẨY, 2 SỐ SAU DẤU PHẨY
	 PRIMARY KEY (MA_NHAP, MA_HANG),
	 CONSTRAINT FK_PHIEU_NHAP FOREIGN KEY (MA_NHAP)
		REFERENCES PHIEU_NHAP(MA_NHAP),
	CONSTRAINT FK_NHAP_HANG FOREIGN KEY (MA_HANG)
		REFERENCES MAT_HANG(MA_HANG)
)
