name: Discord Commit Logger

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn theo dõi

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Lấy commit mới nhất
          COMMIT_INFO=$(git log -1 --pretty=format:"%h - %an: %s")
          
          # Lấy danh sách file thay đổi theo loại
          MODIFIED=$(git diff-tree --no-commit-id --name-status -r HEAD | grep '^M' | awk '{print $2}' | paste -sd "," -)
          ADDED=$(git diff-tree --no-commit-id --name-status -r HEAD | grep '^A' | awk '{print $2}' | paste -sd "," -)
          DELETED=$(git diff-tree --no-commit-id --name-status -r HEAD | grep '^D' | awk '{print $2}' | paste -sd "," -)
          
          # Tạo nội dung thông báo
          MESSAGE="New commit: $COMMIT_INFO\nModified: ${MODIFIED:-None}\nAdded: ${ADDED:-None}\nDeleted: ${DELETED:-None}"
          
          # Gửi lên Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK
